{exec}= require 'child_process'
{spawn,exec}= require 'child_process'

task "build", "build the source in ./src/*.coffe to .", ->
  exec "coffee -c --output . ./src/*.coffee", (err,stdout,stderr) ->
    throw err if err
    console.log stdout + stderr

#task "buildwatch", "build the files and watch for changes", (options) ->
#  exec "coffee -wc --output . ./src/*.coffee", (err,stdout,stderr) ->
#    throw err if err
#    console.log stdout + stderr

task "buildwatch", "build the files and watch for changes", (options) ->
  spawn 'coffee', ['-cw', '-o', '.', './src' ], stdio: 'inherit'


task "docs", "remake documentation", () ->
  exec "docco src/*.coffee"

